YouVersion:
  Overview:
    Hourly: http://placekitten.com/300/200
    Daily:  http://placekitten.com/300/200
    Weekly: http://placekitten.com/300/200
  API:
    Hourly: http://placekitten.com/300/200
    Daily:  http://placekitten.com/300/200
    Weekly: http://placekitten.com/300/200
  www/mdot:
    Hourly: http://placekitten.com/300/200
    Daily:  http://placekitten.com/300/200
    Weekly: http://placekitten.com/300/200
Church Online Platform:
  Overview:
    Hourly: http://placekitten.com/300/200
    Daily:  http://placekitten.com/300/200
    Weekly: http://placekitten.com/300/200
  API:
    Hourly: http://placekitten.com/300/200
    Daily:  http://placekitten.com/300/200
    Weekly: http://placekitten.com/300/200
  www/mdot:
    Hourly: http://placekitten.com/300/200
    Daily:  http://placekitten.com/300/200
