YouVersion:
  Overview:
    Hourly: http://placekitten.com/400/300
    Daily:  http://placekitten.com/400/300
    Weekly: http://placekitten.com/400/300
  API:
    Hourly: http://placekitten.com/400/300
    Daily:  http://placekitten.com/400/300
    Weekly: http://placekitten.com/400/300
  www/mdot:
    Hourly: http://placekitten.com/400/300
    Daily:  http://placekitten.com/400/300
    Weekly: http://placekitten.com/400/300
Church Online Platform:
  Overview:
    Hourly: http://placekitten.com/400/300
    Daily:  http://placekitten.com/400/300
    Weekly: http://placekitten.com/400/300
  API:
    Hourly: http://placekitten.com/400/300
    Daily:  http://placekitten.com/400/300
    Weekly: http://placekitten.com/400/300
  www/mdot:
    Hourly: http://placekitten.com/400/300
    Daily:  http://placekitten.com/400/300
